/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppTimetableRouteImport } from './routes/app.timetable'
import { Route as AppTeachersRouteImport } from './routes/app.teachers'
import { Route as AppStudentsRouteImport } from './routes/app.students'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppScheduleRouteImport } from './routes/app.schedule'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppMeetingsRouteImport } from './routes/app.meetings'
import { Route as AppLogsRouteImport } from './routes/app.logs'
import { Route as AppInfrastructureRouteImport } from './routes/app.infrastructure'
import { Route as AppGradebookRouteImport } from './routes/app.gradebook'
import { Route as AppFeesRouteImport } from './routes/app.fees'
import { Route as AppExamsRouteImport } from './routes/app.exams'
import { Route as AppEventsRouteImport } from './routes/app.events'
import { Route as AppComplianceRouteImport } from './routes/app.compliance'
import { Route as AppCommunicationRouteImport } from './routes/app.communication'
import { Route as AppClassesRouteImport } from './routes/app.classes'
import { Route as AppChildrenRouteImport } from './routes/app.children'
import { Route as AppAttendanceRouteImport } from './routes/app.attendance'
import { Route as AppAssignmentsRouteImport } from './routes/app.assignments'
import { Route as AppAnnouncementsRouteImport } from './routes/app.announcements'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAdmissionsRouteImport } from './routes/app.admissions'
import { Route as AppAcademicsRouteImport } from './routes/app.academics'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTimetableRoute = AppTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AppRoute,
} as any)
const AppTeachersRoute = AppTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingsRoute = AppMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppInfrastructureRoute = AppInfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => AppRoute,
} as any)
const AppGradebookRoute = AppGradebookRouteImport.update({
  id: '/gradebook',
  path: '/gradebook',
  getParentRoute: () => AppRoute,
} as any)
const AppFeesRoute = AppFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AppRoute,
} as any)
const AppExamsRoute = AppExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppComplianceRoute = AppComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunicationRoute = AppCommunicationRouteImport.update({
  id: '/communication',
  path: '/communication',
  getParentRoute: () => AppRoute,
} as any)
const AppClassesRoute = AppClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AppRoute,
} as any)
const AppChildrenRoute = AppChildrenRouteImport.update({
  id: '/children',
  path: '/children',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAssignmentsRoute = AppAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => AppRoute,
} as any)
const AppAnnouncementsRoute = AppAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAdmissionsRoute = AppAdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademicsRoute = AppAcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/academics': typeof AppAcademicsRoute
  '/app/admissions': typeof AppAdmissionsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/assignments': typeof AppAssignmentsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/children': typeof AppChildrenRoute
  '/app/classes': typeof AppClassesRoute
  '/app/communication': typeof AppCommunicationRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/events': typeof AppEventsRoute
  '/app/exams': typeof AppExamsRoute
  '/app/fees': typeof AppFeesRoute
  '/app/gradebook': typeof AppGradebookRoute
  '/app/infrastructure': typeof AppInfrastructureRoute
  '/app/logs': typeof AppLogsRoute
  '/app/meetings': typeof AppMeetingsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/students': typeof AppStudentsRoute
  '/app/teachers': typeof AppTeachersRoute
  '/app/timetable': typeof AppTimetableRoute
  '/app/users': typeof AppUsersRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/academics': typeof AppAcademicsRoute
  '/app/admissions': typeof AppAdmissionsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/assignments': typeof AppAssignmentsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/children': typeof AppChildrenRoute
  '/app/classes': typeof AppClassesRoute
  '/app/communication': typeof AppCommunicationRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/events': typeof AppEventsRoute
  '/app/exams': typeof AppExamsRoute
  '/app/fees': typeof AppFeesRoute
  '/app/gradebook': typeof AppGradebookRoute
  '/app/infrastructure': typeof AppInfrastructureRoute
  '/app/logs': typeof AppLogsRoute
  '/app/meetings': typeof AppMeetingsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/students': typeof AppStudentsRoute
  '/app/teachers': typeof AppTeachersRoute
  '/app/timetable': typeof AppTimetableRoute
  '/app/users': typeof AppUsersRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/academics': typeof AppAcademicsRoute
  '/app/admissions': typeof AppAdmissionsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/assignments': typeof AppAssignmentsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/children': typeof AppChildrenRoute
  '/app/classes': typeof AppClassesRoute
  '/app/communication': typeof AppCommunicationRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/events': typeof AppEventsRoute
  '/app/exams': typeof AppExamsRoute
  '/app/fees': typeof AppFeesRoute
  '/app/gradebook': typeof AppGradebookRoute
  '/app/infrastructure': typeof AppInfrastructureRoute
  '/app/logs': typeof AppLogsRoute
  '/app/meetings': typeof AppMeetingsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/students': typeof AppStudentsRoute
  '/app/teachers': typeof AppTeachersRoute
  '/app/timetable': typeof AppTimetableRoute
  '/app/users': typeof AppUsersRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/academics'
    | '/app/admissions'
    | '/app/analytics'
    | '/app/announcements'
    | '/app/assignments'
    | '/app/attendance'
    | '/app/children'
    | '/app/classes'
    | '/app/communication'
    | '/app/compliance'
    | '/app/events'
    | '/app/exams'
    | '/app/fees'
    | '/app/gradebook'
    | '/app/infrastructure'
    | '/app/logs'
    | '/app/meetings'
    | '/app/profile'
    | '/app/reports'
    | '/app/schedule'
    | '/app/settings'
    | '/app/students'
    | '/app/teachers'
    | '/app/timetable'
    | '/app/users'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/academics'
    | '/app/admissions'
    | '/app/analytics'
    | '/app/announcements'
    | '/app/assignments'
    | '/app/attendance'
    | '/app/children'
    | '/app/classes'
    | '/app/communication'
    | '/app/compliance'
    | '/app/events'
    | '/app/exams'
    | '/app/fees'
    | '/app/gradebook'
    | '/app/infrastructure'
    | '/app/logs'
    | '/app/meetings'
    | '/app/profile'
    | '/app/reports'
    | '/app/schedule'
    | '/app/settings'
    | '/app/students'
    | '/app/teachers'
    | '/app/timetable'
    | '/app/users'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/academics'
    | '/app/admissions'
    | '/app/analytics'
    | '/app/announcements'
    | '/app/assignments'
    | '/app/attendance'
    | '/app/children'
    | '/app/classes'
    | '/app/communication'
    | '/app/compliance'
    | '/app/events'
    | '/app/exams'
    | '/app/fees'
    | '/app/gradebook'
    | '/app/infrastructure'
    | '/app/logs'
    | '/app/meetings'
    | '/app/profile'
    | '/app/reports'
    | '/app/schedule'
    | '/app/settings'
    | '/app/students'
    | '/app/teachers'
    | '/app/timetable'
    | '/app/users'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/timetable': {
      id: '/app/timetable'
      path: '/timetable'
      fullPath: '/app/timetable'
      preLoaderRoute: typeof AppTimetableRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teachers': {
      id: '/app/teachers'
      path: '/teachers'
      fullPath: '/app/teachers'
      preLoaderRoute: typeof AppTeachersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/students': {
      id: '/app/students'
      path: '/students'
      fullPath: '/app/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/schedule': {
      id: '/app/schedule'
      path: '/schedule'
      fullPath: '/app/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/meetings': {
      id: '/app/meetings'
      path: '/meetings'
      fullPath: '/app/meetings'
      preLoaderRoute: typeof AppMeetingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/logs': {
      id: '/app/logs'
      path: '/logs'
      fullPath: '/app/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/infrastructure': {
      id: '/app/infrastructure'
      path: '/infrastructure'
      fullPath: '/app/infrastructure'
      preLoaderRoute: typeof AppInfrastructureRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/gradebook': {
      id: '/app/gradebook'
      path: '/gradebook'
      fullPath: '/app/gradebook'
      preLoaderRoute: typeof AppGradebookRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fees': {
      id: '/app/fees'
      path: '/fees'
      fullPath: '/app/fees'
      preLoaderRoute: typeof AppFeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/exams': {
      id: '/app/exams'
      path: '/exams'
      fullPath: '/app/exams'
      preLoaderRoute: typeof AppExamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/events': {
      id: '/app/events'
      path: '/events'
      fullPath: '/app/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compliance': {
      id: '/app/compliance'
      path: '/compliance'
      fullPath: '/app/compliance'
      preLoaderRoute: typeof AppComplianceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/communication': {
      id: '/app/communication'
      path: '/communication'
      fullPath: '/app/communication'
      preLoaderRoute: typeof AppCommunicationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/classes': {
      id: '/app/classes'
      path: '/classes'
      fullPath: '/app/classes'
      preLoaderRoute: typeof AppClassesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/children': {
      id: '/app/children'
      path: '/children'
      fullPath: '/app/children'
      preLoaderRoute: typeof AppChildrenRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/attendance': {
      id: '/app/attendance'
      path: '/attendance'
      fullPath: '/app/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assignments': {
      id: '/app/assignments'
      path: '/assignments'
      fullPath: '/app/assignments'
      preLoaderRoute: typeof AppAssignmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/announcements': {
      id: '/app/announcements'
      path: '/announcements'
      fullPath: '/app/announcements'
      preLoaderRoute: typeof AppAnnouncementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admissions': {
      id: '/app/admissions'
      path: '/admissions'
      fullPath: '/app/admissions'
      preLoaderRoute: typeof AppAdmissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/academics': {
      id: '/app/academics'
      path: '/academics'
      fullPath: '/app/academics'
      preLoaderRoute: typeof AppAcademicsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAcademicsRoute: typeof AppAcademicsRoute
  AppAdmissionsRoute: typeof AppAdmissionsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAnnouncementsRoute: typeof AppAnnouncementsRoute
  AppAssignmentsRoute: typeof AppAssignmentsRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppChildrenRoute: typeof AppChildrenRoute
  AppClassesRoute: typeof AppClassesRoute
  AppCommunicationRoute: typeof AppCommunicationRoute
  AppComplianceRoute: typeof AppComplianceRoute
  AppEventsRoute: typeof AppEventsRoute
  AppExamsRoute: typeof AppExamsRoute
  AppFeesRoute: typeof AppFeesRoute
  AppGradebookRoute: typeof AppGradebookRoute
  AppInfrastructureRoute: typeof AppInfrastructureRoute
  AppLogsRoute: typeof AppLogsRoute
  AppMeetingsRoute: typeof AppMeetingsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStudentsRoute: typeof AppStudentsRoute
  AppTeachersRoute: typeof AppTeachersRoute
  AppTimetableRoute: typeof AppTimetableRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAcademicsRoute: AppAcademicsRoute,
  AppAdmissionsRoute: AppAdmissionsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAnnouncementsRoute: AppAnnouncementsRoute,
  AppAssignmentsRoute: AppAssignmentsRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppChildrenRoute: AppChildrenRoute,
  AppClassesRoute: AppClassesRoute,
  AppCommunicationRoute: AppCommunicationRoute,
  AppComplianceRoute: AppComplianceRoute,
  AppEventsRoute: AppEventsRoute,
  AppExamsRoute: AppExamsRoute,
  AppFeesRoute: AppFeesRoute,
  AppGradebookRoute: AppGradebookRoute,
  AppInfrastructureRoute: AppInfrastructureRoute,
  AppLogsRoute: AppLogsRoute,
  AppMeetingsRoute: AppMeetingsRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStudentsRoute: AppStudentsRoute,
  AppTeachersRoute: AppTeachersRoute,
  AppTimetableRoute: AppTimetableRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
