/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppTimetableRouteImport } from './routes/app.timetable'
import { Route as AppTeachersRouteImport } from './routes/app.teachers'
import { Route as AppSubjectsRouteImport } from './routes/app.subjects'
import { Route as AppStudyResourcesRouteImport } from './routes/app.study-resources'
import { Route as AppStudentsRouteImport } from './routes/app.students'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppScheduleRouteImport } from './routes/app.schedule'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppPerformanceRouteImport } from './routes/app.performance'
import { Route as AppMessagesRouteImport } from './routes/app.messages'
import { Route as AppMeetingsRouteImport } from './routes/app.meetings'
import { Route as AppLogsRouteImport } from './routes/app.logs'
import { Route as AppInfrastructureRouteImport } from './routes/app.infrastructure'
import { Route as AppGradebookRouteImport } from './routes/app.gradebook'
import { Route as AppFeesRouteImport } from './routes/app.fees'
import { Route as AppFacilitiesRouteImport } from './routes/app.facilities'
import { Route as AppExamsRouteImport } from './routes/app.exams'
import { Route as AppEventsRouteImport } from './routes/app.events'
import { Route as AppDocumentsRouteImport } from './routes/app.documents'
import { Route as AppComplianceRouteImport } from './routes/app.compliance'
import { Route as AppCommunicationRouteImport } from './routes/app.communication'
import { Route as AppClassesRouteImport } from './routes/app.classes'
import { Route as AppChildrenRouteImport } from './routes/app.children'
import { Route as AppBrainRouteImport } from './routes/app.brain'
import { Route as AppAttendanceRouteImport } from './routes/app.attendance'
import { Route as AppAssignmentsRouteImport } from './routes/app.assignments'
import { Route as AppAnnouncementsRouteImport } from './routes/app.announcements'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAiRouteImport } from './routes/app.ai'
import { Route as AppAdmissionsRouteImport } from './routes/app.admissions'
import { Route as AppAcademicsRouteImport } from './routes/app.academics'
import { Route as AppAdminStudentsRouteImport } from './routes/app.admin.students'
import { Route as AppAdminStaffRouteImport } from './routes/app.admin.staff'
import { Route as AppAdminOperationsRouteImport } from './routes/app.admin.operations'
import { Route as AppAdminFeesRouteImport } from './routes/app.admin.fees'
import { Route as AppAdminFacilitiesRouteImport } from './routes/app.admin.facilities'
import { Route as AppAdminDocumentsRouteImport } from './routes/app.admin.documents'
import { Route as AppAdminComplianceRouteImport } from './routes/app.admin.compliance'
import { Route as AppAdminBrainRouteImport } from './routes/app.admin.brain'
import { Route as AppAdminAnalyticsRouteImport } from './routes/app.admin.analytics'
import { Route as AppAdminAiRouteImport } from './routes/app.admin.ai'
import { Route as AppAdminAcademicsRouteImport } from './routes/app.admin.academics'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTimetableRoute = AppTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AppRoute,
} as any)
const AppTeachersRoute = AppTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AppRoute,
} as any)
const AppSubjectsRoute = AppSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AppRoute,
} as any)
const AppStudyResourcesRoute = AppStudyResourcesRouteImport.update({
  id: '/study-resources',
  path: '/study-resources',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceRoute = AppPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingsRoute = AppMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppInfrastructureRoute = AppInfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => AppRoute,
} as any)
const AppGradebookRoute = AppGradebookRouteImport.update({
  id: '/gradebook',
  path: '/gradebook',
  getParentRoute: () => AppRoute,
} as any)
const AppFeesRoute = AppFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AppRoute,
} as any)
const AppFacilitiesRoute = AppFacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => AppRoute,
} as any)
const AppExamsRoute = AppExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppComplianceRoute = AppComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunicationRoute = AppCommunicationRouteImport.update({
  id: '/communication',
  path: '/communication',
  getParentRoute: () => AppRoute,
} as any)
const AppClassesRoute = AppClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AppRoute,
} as any)
const AppChildrenRoute = AppChildrenRouteImport.update({
  id: '/children',
  path: '/children',
  getParentRoute: () => AppRoute,
} as any)
const AppBrainRoute = AppBrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAssignmentsRoute = AppAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => AppRoute,
} as any)
const AppAnnouncementsRoute = AppAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppAdmissionsRoute = AppAdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademicsRoute = AppAcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminStudentsRoute = AppAdminStudentsRouteImport.update({
  id: '/admin/students',
  path: '/admin/students',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminStaffRoute = AppAdminStaffRouteImport.update({
  id: '/admin/staff',
  path: '/admin/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminOperationsRoute = AppAdminOperationsRouteImport.update({
  id: '/admin/operations',
  path: '/admin/operations',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminFeesRoute = AppAdminFeesRouteImport.update({
  id: '/admin/fees',
  path: '/admin/fees',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminFacilitiesRoute = AppAdminFacilitiesRouteImport.update({
  id: '/admin/facilities',
  path: '/admin/facilities',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDocumentsRoute = AppAdminDocumentsRouteImport.update({
  id: '/admin/documents',
  path: '/admin/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminComplianceRoute = AppAdminComplianceRouteImport.update({
  id: '/admin/compliance',
  path: '/admin/compliance',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminBrainRoute = AppAdminBrainRouteImport.update({
  id: '/admin/brain',
  path: '/admin/brain',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAnalyticsRoute = AppAdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAiRoute = AppAdminAiRouteImport.update({
  id: '/admin/ai',
  path: '/admin/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAcademicsRoute = AppAdminAcademicsRouteImport.update({
  id: '/admin/academics',
  path: '/admin/academics',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/academics': typeof AppAcademicsRoute
  '/app/admissions': typeof AppAdmissionsRoute
  '/app/ai': typeof AppAiRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/assignments': typeof AppAssignmentsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/brain': typeof AppBrainRoute
  '/app/children': typeof AppChildrenRoute
  '/app/classes': typeof AppClassesRoute
  '/app/communication': typeof AppCommunicationRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/events': typeof AppEventsRoute
  '/app/exams': typeof AppExamsRoute
  '/app/facilities': typeof AppFacilitiesRoute
  '/app/fees': typeof AppFeesRoute
  '/app/gradebook': typeof AppGradebookRoute
  '/app/infrastructure': typeof AppInfrastructureRoute
  '/app/logs': typeof AppLogsRoute
  '/app/meetings': typeof AppMeetingsRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/students': typeof AppStudentsRoute
  '/app/study-resources': typeof AppStudyResourcesRoute
  '/app/subjects': typeof AppSubjectsRoute
  '/app/teachers': typeof AppTeachersRoute
  '/app/timetable': typeof AppTimetableRoute
  '/app/users': typeof AppUsersRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/academics': typeof AppAdminAcademicsRoute
  '/app/admin/ai': typeof AppAdminAiRoute
  '/app/admin/analytics': typeof AppAdminAnalyticsRoute
  '/app/admin/brain': typeof AppAdminBrainRoute
  '/app/admin/compliance': typeof AppAdminComplianceRoute
  '/app/admin/documents': typeof AppAdminDocumentsRoute
  '/app/admin/facilities': typeof AppAdminFacilitiesRoute
  '/app/admin/fees': typeof AppAdminFeesRoute
  '/app/admin/operations': typeof AppAdminOperationsRoute
  '/app/admin/staff': typeof AppAdminStaffRoute
  '/app/admin/students': typeof AppAdminStudentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/academics': typeof AppAcademicsRoute
  '/app/admissions': typeof AppAdmissionsRoute
  '/app/ai': typeof AppAiRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/assignments': typeof AppAssignmentsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/brain': typeof AppBrainRoute
  '/app/children': typeof AppChildrenRoute
  '/app/classes': typeof AppClassesRoute
  '/app/communication': typeof AppCommunicationRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/events': typeof AppEventsRoute
  '/app/exams': typeof AppExamsRoute
  '/app/facilities': typeof AppFacilitiesRoute
  '/app/fees': typeof AppFeesRoute
  '/app/gradebook': typeof AppGradebookRoute
  '/app/infrastructure': typeof AppInfrastructureRoute
  '/app/logs': typeof AppLogsRoute
  '/app/meetings': typeof AppMeetingsRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/students': typeof AppStudentsRoute
  '/app/study-resources': typeof AppStudyResourcesRoute
  '/app/subjects': typeof AppSubjectsRoute
  '/app/teachers': typeof AppTeachersRoute
  '/app/timetable': typeof AppTimetableRoute
  '/app/users': typeof AppUsersRoute
  '/app': typeof AppIndexRoute
  '/app/admin/academics': typeof AppAdminAcademicsRoute
  '/app/admin/ai': typeof AppAdminAiRoute
  '/app/admin/analytics': typeof AppAdminAnalyticsRoute
  '/app/admin/brain': typeof AppAdminBrainRoute
  '/app/admin/compliance': typeof AppAdminComplianceRoute
  '/app/admin/documents': typeof AppAdminDocumentsRoute
  '/app/admin/facilities': typeof AppAdminFacilitiesRoute
  '/app/admin/fees': typeof AppAdminFeesRoute
  '/app/admin/operations': typeof AppAdminOperationsRoute
  '/app/admin/staff': typeof AppAdminStaffRoute
  '/app/admin/students': typeof AppAdminStudentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/academics': typeof AppAcademicsRoute
  '/app/admissions': typeof AppAdmissionsRoute
  '/app/ai': typeof AppAiRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/assignments': typeof AppAssignmentsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/brain': typeof AppBrainRoute
  '/app/children': typeof AppChildrenRoute
  '/app/classes': typeof AppClassesRoute
  '/app/communication': typeof AppCommunicationRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/events': typeof AppEventsRoute
  '/app/exams': typeof AppExamsRoute
  '/app/facilities': typeof AppFacilitiesRoute
  '/app/fees': typeof AppFeesRoute
  '/app/gradebook': typeof AppGradebookRoute
  '/app/infrastructure': typeof AppInfrastructureRoute
  '/app/logs': typeof AppLogsRoute
  '/app/meetings': typeof AppMeetingsRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/students': typeof AppStudentsRoute
  '/app/study-resources': typeof AppStudyResourcesRoute
  '/app/subjects': typeof AppSubjectsRoute
  '/app/teachers': typeof AppTeachersRoute
  '/app/timetable': typeof AppTimetableRoute
  '/app/users': typeof AppUsersRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/academics': typeof AppAdminAcademicsRoute
  '/app/admin/ai': typeof AppAdminAiRoute
  '/app/admin/analytics': typeof AppAdminAnalyticsRoute
  '/app/admin/brain': typeof AppAdminBrainRoute
  '/app/admin/compliance': typeof AppAdminComplianceRoute
  '/app/admin/documents': typeof AppAdminDocumentsRoute
  '/app/admin/facilities': typeof AppAdminFacilitiesRoute
  '/app/admin/fees': typeof AppAdminFeesRoute
  '/app/admin/operations': typeof AppAdminOperationsRoute
  '/app/admin/staff': typeof AppAdminStaffRoute
  '/app/admin/students': typeof AppAdminStudentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/academics'
    | '/app/admissions'
    | '/app/ai'
    | '/app/analytics'
    | '/app/announcements'
    | '/app/assignments'
    | '/app/attendance'
    | '/app/brain'
    | '/app/children'
    | '/app/classes'
    | '/app/communication'
    | '/app/compliance'
    | '/app/documents'
    | '/app/events'
    | '/app/exams'
    | '/app/facilities'
    | '/app/fees'
    | '/app/gradebook'
    | '/app/infrastructure'
    | '/app/logs'
    | '/app/meetings'
    | '/app/messages'
    | '/app/performance'
    | '/app/profile'
    | '/app/reports'
    | '/app/schedule'
    | '/app/settings'
    | '/app/students'
    | '/app/study-resources'
    | '/app/subjects'
    | '/app/teachers'
    | '/app/timetable'
    | '/app/users'
    | '/app/'
    | '/app/admin/academics'
    | '/app/admin/ai'
    | '/app/admin/analytics'
    | '/app/admin/brain'
    | '/app/admin/compliance'
    | '/app/admin/documents'
    | '/app/admin/facilities'
    | '/app/admin/fees'
    | '/app/admin/operations'
    | '/app/admin/staff'
    | '/app/admin/students'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/academics'
    | '/app/admissions'
    | '/app/ai'
    | '/app/analytics'
    | '/app/announcements'
    | '/app/assignments'
    | '/app/attendance'
    | '/app/brain'
    | '/app/children'
    | '/app/classes'
    | '/app/communication'
    | '/app/compliance'
    | '/app/documents'
    | '/app/events'
    | '/app/exams'
    | '/app/facilities'
    | '/app/fees'
    | '/app/gradebook'
    | '/app/infrastructure'
    | '/app/logs'
    | '/app/meetings'
    | '/app/messages'
    | '/app/performance'
    | '/app/profile'
    | '/app/reports'
    | '/app/schedule'
    | '/app/settings'
    | '/app/students'
    | '/app/study-resources'
    | '/app/subjects'
    | '/app/teachers'
    | '/app/timetable'
    | '/app/users'
    | '/app'
    | '/app/admin/academics'
    | '/app/admin/ai'
    | '/app/admin/analytics'
    | '/app/admin/brain'
    | '/app/admin/compliance'
    | '/app/admin/documents'
    | '/app/admin/facilities'
    | '/app/admin/fees'
    | '/app/admin/operations'
    | '/app/admin/staff'
    | '/app/admin/students'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/academics'
    | '/app/admissions'
    | '/app/ai'
    | '/app/analytics'
    | '/app/announcements'
    | '/app/assignments'
    | '/app/attendance'
    | '/app/brain'
    | '/app/children'
    | '/app/classes'
    | '/app/communication'
    | '/app/compliance'
    | '/app/documents'
    | '/app/events'
    | '/app/exams'
    | '/app/facilities'
    | '/app/fees'
    | '/app/gradebook'
    | '/app/infrastructure'
    | '/app/logs'
    | '/app/meetings'
    | '/app/messages'
    | '/app/performance'
    | '/app/profile'
    | '/app/reports'
    | '/app/schedule'
    | '/app/settings'
    | '/app/students'
    | '/app/study-resources'
    | '/app/subjects'
    | '/app/teachers'
    | '/app/timetable'
    | '/app/users'
    | '/app/'
    | '/app/admin/academics'
    | '/app/admin/ai'
    | '/app/admin/analytics'
    | '/app/admin/brain'
    | '/app/admin/compliance'
    | '/app/admin/documents'
    | '/app/admin/facilities'
    | '/app/admin/fees'
    | '/app/admin/operations'
    | '/app/admin/staff'
    | '/app/admin/students'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/timetable': {
      id: '/app/timetable'
      path: '/timetable'
      fullPath: '/app/timetable'
      preLoaderRoute: typeof AppTimetableRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teachers': {
      id: '/app/teachers'
      path: '/teachers'
      fullPath: '/app/teachers'
      preLoaderRoute: typeof AppTeachersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/subjects': {
      id: '/app/subjects'
      path: '/subjects'
      fullPath: '/app/subjects'
      preLoaderRoute: typeof AppSubjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/study-resources': {
      id: '/app/study-resources'
      path: '/study-resources'
      fullPath: '/app/study-resources'
      preLoaderRoute: typeof AppStudyResourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/students': {
      id: '/app/students'
      path: '/students'
      fullPath: '/app/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/schedule': {
      id: '/app/schedule'
      path: '/schedule'
      fullPath: '/app/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/performance': {
      id: '/app/performance'
      path: '/performance'
      fullPath: '/app/performance'
      preLoaderRoute: typeof AppPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/meetings': {
      id: '/app/meetings'
      path: '/meetings'
      fullPath: '/app/meetings'
      preLoaderRoute: typeof AppMeetingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/logs': {
      id: '/app/logs'
      path: '/logs'
      fullPath: '/app/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/infrastructure': {
      id: '/app/infrastructure'
      path: '/infrastructure'
      fullPath: '/app/infrastructure'
      preLoaderRoute: typeof AppInfrastructureRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/gradebook': {
      id: '/app/gradebook'
      path: '/gradebook'
      fullPath: '/app/gradebook'
      preLoaderRoute: typeof AppGradebookRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fees': {
      id: '/app/fees'
      path: '/fees'
      fullPath: '/app/fees'
      preLoaderRoute: typeof AppFeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/facilities': {
      id: '/app/facilities'
      path: '/facilities'
      fullPath: '/app/facilities'
      preLoaderRoute: typeof AppFacilitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/exams': {
      id: '/app/exams'
      path: '/exams'
      fullPath: '/app/exams'
      preLoaderRoute: typeof AppExamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/events': {
      id: '/app/events'
      path: '/events'
      fullPath: '/app/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compliance': {
      id: '/app/compliance'
      path: '/compliance'
      fullPath: '/app/compliance'
      preLoaderRoute: typeof AppComplianceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/communication': {
      id: '/app/communication'
      path: '/communication'
      fullPath: '/app/communication'
      preLoaderRoute: typeof AppCommunicationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/classes': {
      id: '/app/classes'
      path: '/classes'
      fullPath: '/app/classes'
      preLoaderRoute: typeof AppClassesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/children': {
      id: '/app/children'
      path: '/children'
      fullPath: '/app/children'
      preLoaderRoute: typeof AppChildrenRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/brain': {
      id: '/app/brain'
      path: '/brain'
      fullPath: '/app/brain'
      preLoaderRoute: typeof AppBrainRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/attendance': {
      id: '/app/attendance'
      path: '/attendance'
      fullPath: '/app/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assignments': {
      id: '/app/assignments'
      path: '/assignments'
      fullPath: '/app/assignments'
      preLoaderRoute: typeof AppAssignmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/announcements': {
      id: '/app/announcements'
      path: '/announcements'
      fullPath: '/app/announcements'
      preLoaderRoute: typeof AppAnnouncementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai': {
      id: '/app/ai'
      path: '/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admissions': {
      id: '/app/admissions'
      path: '/admissions'
      fullPath: '/app/admissions'
      preLoaderRoute: typeof AppAdmissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/academics': {
      id: '/app/academics'
      path: '/academics'
      fullPath: '/app/academics'
      preLoaderRoute: typeof AppAcademicsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/students': {
      id: '/app/admin/students'
      path: '/admin/students'
      fullPath: '/app/admin/students'
      preLoaderRoute: typeof AppAdminStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/staff': {
      id: '/app/admin/staff'
      path: '/admin/staff'
      fullPath: '/app/admin/staff'
      preLoaderRoute: typeof AppAdminStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/operations': {
      id: '/app/admin/operations'
      path: '/admin/operations'
      fullPath: '/app/admin/operations'
      preLoaderRoute: typeof AppAdminOperationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/fees': {
      id: '/app/admin/fees'
      path: '/admin/fees'
      fullPath: '/app/admin/fees'
      preLoaderRoute: typeof AppAdminFeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/facilities': {
      id: '/app/admin/facilities'
      path: '/admin/facilities'
      fullPath: '/app/admin/facilities'
      preLoaderRoute: typeof AppAdminFacilitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/documents': {
      id: '/app/admin/documents'
      path: '/admin/documents'
      fullPath: '/app/admin/documents'
      preLoaderRoute: typeof AppAdminDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/compliance': {
      id: '/app/admin/compliance'
      path: '/admin/compliance'
      fullPath: '/app/admin/compliance'
      preLoaderRoute: typeof AppAdminComplianceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/brain': {
      id: '/app/admin/brain'
      path: '/admin/brain'
      fullPath: '/app/admin/brain'
      preLoaderRoute: typeof AppAdminBrainRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/analytics': {
      id: '/app/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/app/admin/analytics'
      preLoaderRoute: typeof AppAdminAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/ai': {
      id: '/app/admin/ai'
      path: '/admin/ai'
      fullPath: '/app/admin/ai'
      preLoaderRoute: typeof AppAdminAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/academics': {
      id: '/app/admin/academics'
      path: '/admin/academics'
      fullPath: '/app/admin/academics'
      preLoaderRoute: typeof AppAdminAcademicsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAcademicsRoute: typeof AppAcademicsRoute
  AppAdmissionsRoute: typeof AppAdmissionsRoute
  AppAiRoute: typeof AppAiRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAnnouncementsRoute: typeof AppAnnouncementsRoute
  AppAssignmentsRoute: typeof AppAssignmentsRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppBrainRoute: typeof AppBrainRoute
  AppChildrenRoute: typeof AppChildrenRoute
  AppClassesRoute: typeof AppClassesRoute
  AppCommunicationRoute: typeof AppCommunicationRoute
  AppComplianceRoute: typeof AppComplianceRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppEventsRoute: typeof AppEventsRoute
  AppExamsRoute: typeof AppExamsRoute
  AppFacilitiesRoute: typeof AppFacilitiesRoute
  AppFeesRoute: typeof AppFeesRoute
  AppGradebookRoute: typeof AppGradebookRoute
  AppInfrastructureRoute: typeof AppInfrastructureRoute
  AppLogsRoute: typeof AppLogsRoute
  AppMeetingsRoute: typeof AppMeetingsRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppPerformanceRoute: typeof AppPerformanceRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStudentsRoute: typeof AppStudentsRoute
  AppStudyResourcesRoute: typeof AppStudyResourcesRoute
  AppSubjectsRoute: typeof AppSubjectsRoute
  AppTeachersRoute: typeof AppTeachersRoute
  AppTimetableRoute: typeof AppTimetableRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminAcademicsRoute: typeof AppAdminAcademicsRoute
  AppAdminAiRoute: typeof AppAdminAiRoute
  AppAdminAnalyticsRoute: typeof AppAdminAnalyticsRoute
  AppAdminBrainRoute: typeof AppAdminBrainRoute
  AppAdminComplianceRoute: typeof AppAdminComplianceRoute
  AppAdminDocumentsRoute: typeof AppAdminDocumentsRoute
  AppAdminFacilitiesRoute: typeof AppAdminFacilitiesRoute
  AppAdminFeesRoute: typeof AppAdminFeesRoute
  AppAdminOperationsRoute: typeof AppAdminOperationsRoute
  AppAdminStaffRoute: typeof AppAdminStaffRoute
  AppAdminStudentsRoute: typeof AppAdminStudentsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAcademicsRoute: AppAcademicsRoute,
  AppAdmissionsRoute: AppAdmissionsRoute,
  AppAiRoute: AppAiRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAnnouncementsRoute: AppAnnouncementsRoute,
  AppAssignmentsRoute: AppAssignmentsRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppBrainRoute: AppBrainRoute,
  AppChildrenRoute: AppChildrenRoute,
  AppClassesRoute: AppClassesRoute,
  AppCommunicationRoute: AppCommunicationRoute,
  AppComplianceRoute: AppComplianceRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppEventsRoute: AppEventsRoute,
  AppExamsRoute: AppExamsRoute,
  AppFacilitiesRoute: AppFacilitiesRoute,
  AppFeesRoute: AppFeesRoute,
  AppGradebookRoute: AppGradebookRoute,
  AppInfrastructureRoute: AppInfrastructureRoute,
  AppLogsRoute: AppLogsRoute,
  AppMeetingsRoute: AppMeetingsRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppPerformanceRoute: AppPerformanceRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStudentsRoute: AppStudentsRoute,
  AppStudyResourcesRoute: AppStudyResourcesRoute,
  AppSubjectsRoute: AppSubjectsRoute,
  AppTeachersRoute: AppTeachersRoute,
  AppTimetableRoute: AppTimetableRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminAcademicsRoute: AppAdminAcademicsRoute,
  AppAdminAiRoute: AppAdminAiRoute,
  AppAdminAnalyticsRoute: AppAdminAnalyticsRoute,
  AppAdminBrainRoute: AppAdminBrainRoute,
  AppAdminComplianceRoute: AppAdminComplianceRoute,
  AppAdminDocumentsRoute: AppAdminDocumentsRoute,
  AppAdminFacilitiesRoute: AppAdminFacilitiesRoute,
  AppAdminFeesRoute: AppAdminFeesRoute,
  AppAdminOperationsRoute: AppAdminOperationsRoute,
  AppAdminStaffRoute: AppAdminStaffRoute,
  AppAdminStudentsRoute: AppAdminStudentsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
